# -*- coding: utf-8 -*-
"""liberdade-econ-mica-pibpc-e-desemprego-proj-3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kSkMfKwvgf_7Yf0GiJIpcv17knYaAdZH
"""

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))
        
import seaborn as sns

"""# **Liberdade Econômica, PIB per capita e Desemprego***

Um debate quente ultimamente com toda essa polarização é sobre os benefícios da liberdade econômica de um país. 
Perguntas como:

*  É bom privatizar as empresas?

*  O governo deve intervir na economia?

Diante essas perguntas quero mostrar algumas modelos de regressão que fiz e avaliar a relação de liberdade econômica e o PIB per capita e taxa de desemprego de um país. 

Quando acabar de ler esse post tenho certeza que você vai estar bem melhor para encarar aquela discussão no churrasco da família (ou não, rs). 

Vem comigo!


## **Dados**

###**Índice de Liberdade Econômica**
Os dados sobre liberdade econômica foi retirado de um índice calculado pela Fraser Institute. Esse índice mensura o quanto as políticas e as instituições do país serve de suporte para a liberdade econômica. 

A Fraser se debruçou sobre 5 abordagens para calcular esse índice:


1.   Tamanho do Governo
2.   Sistema Legal e Direito de Propriedade
3.   Moeda Forte
4.   Liberdade para Trocas Internacionais
5.   Regularização

Vou deixar o link aqui (https://www.fraserinstitute.org/studies/economic-freedom-of-the-world-2019-annual-report) para caso você queira se aprofundar. Te encorajo fortemente, pois vou deixar esse espaço para mostrar os resultados principalmente sem focar muito na teoria.

### **PIB per capita e Desemprego**

Peguei os dados do PIB per capita e desemprego por meio do site do FED (Sistema de Reserva Federal dos Estados Unidos).

OBS: Todos os dados foram coletados para o ano de 2016.



Agora chegou a hora da prática!!

## **A Regressão**
"""

import pandas as pd
import statsmodels.formula.api as smf
import numpy as np

efw = pd.read_csv('/kaggle/input/efw-cc/efw_cc-1.csv')
efw.head()

#Renomeando a coluna do índice de liberdade eco.
efw.rename(columns = {'ECONOMIC FREEDOM': 'freedom'}, inplace=True)


efw = efw[['freedom', "pib_per_cap", "taxa_desemprego"]]
efw.head()

efw.describe().T

sns.pairplot(efw, x_vars = ["pib_per_cap", "taxa_desemprego"], y_vars= ['freedom'], kind= 'reg', diag_kind = None)

"""### **Aplicando a Regressão Linear**

Vamos utilizar os seguintes modelos para estimação:

$$pib = \beta_0 + \beta_1*freedom$$

$$txdesemprego = \beta_0 + \beta_1*freedom$$
"""

#Apagando os valores NaN para não ter erros na regressão.
efw = efw.dropna(subset=['pib_per_cap', 'freedom'], how='any')
efw = efw.dropna(subset=['taxa_desemprego', 'freedom'], how='any')

#Alguns valores NaN estavam como 0 na coluna de tx desemprego
efw_u = efw[efw['taxa_desemprego'] > 0] 

#Regressão (pib = beta_0 + beta_1*freedom)
MQO_efw = smf.ols('pib_per_cap ~ freedom', data=efw)
results = MQO_efw.fit()

#Regressão (tx_desemprego = beta_0 + beta_1*freedom)
MQO_efw2 = smf.ols('taxa_desemprego ~ freedom', data=efw_u)
results2 = MQO_efw2.fit()

"""## **Resultados**

#### **Resultados Regressão PIB ~ Liberdade**
"""

results.summary()

"""O modelo estimado é
$$ pib = -7.4734 + 1.2846*freedom$$

O que indica uma **correlação positiva** entre a liberdade econômica e PIB per capita. 

Pelos resultados notamos também que o $R^2 \approx 0.1$.
Um valor não tão alto. O que indica um grau de ajuste não tão bom. Mas, como estamos pensando em inferência, não é um grande problema. Pelo P-valor (0.000) nota se que o parâmetro de 'freedom' é estatisticamente relevante.

#### **Resultados Regressão Tx. Desemprego ~ Liberdade**
"""

results2.summary()

"""O modelo estimado é
$$ txdesemp = 18.1 -1.4392*freedom$$

O que indica uma **correlação negativa** entre liberdade econômica e taxa de desemprego. Então, um aumento na liberdade geraria menos desemprego.

Pelos resultados notamos também que o $R^2 \approx 0.062$.
Um valor não tão alto. O que indica um grau de ajuste não tão bom. Contudo, pelo P-valor nota se que o parâmetro de 'freedom' é estatisticamente relevante a 0.9%.

Nossos modelos deu um ajuste muito baixo e devemos ser cautelos em tomar uma conclusão. Provavelmente temos problema de especificação dos dados, ainda existe muitas outras variáveis que afetam essas variáveis dependentes. Mas, a partir deles notamos que liberdade econômica é bom para aumentar riqueza per capita e um menor desemprego. Nos dois modelos os parâmetros são estatisticamente significantes, o que nos leva a crer que a relação é coerente.

Agora, já pode chegar no churrasco e arrasar (ou não se sua espectativa era outra) ! (rs) Mas, tome cuidado! Sempre há um outro lado da moeda. Maior eficiência é inversamente proporcional a igualdade, algo muito importante também. Logo, embora maior liberdade econômica gera maior produto e renda, mas não quer dizer que o ideal é ser totalmente livre!


Até mais!
"""

# efw = efw[(efw['pib_per_cap'] != 0) & (efw['taxa_desemprego'] != 0)]

#Regressão (pib = beta_0 + beta_1*freedom)
# MQO_efw = smf.ols('np.log(pib_per_cap) ~ freedom', data=efw)
# results = MQO_efw.fit()

# #Regressão (tx_desemprego = beta_0 + beta_1*freedom)
# MQO_efw2 = smf.ols('np.log(taxa_desemprego) ~ freedom', data=efw_u)
# results2 = MQO_efw2.fit()

# results2.summary()